server:
  port: 9527

spring:
  application:
    name: cloud-gateway-9527
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2021?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    gateway:
      routes:
         id: payment-001
         uri: http://localhost:8001
         predicate:

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka