server:
  port: 9527

spring:
  application:
    name: cloud-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
         - id: payment-001
           #uri: http://localhost:8001
           uri: lb://CLOUD-PAYMENT-SERVICE
           predicates:
             - Path=/payment/get/***
         - id: payment-002
           #uri: http://localhost:8001
           uri: lb://CLOUD-PAYMENT-SERVICE
           predicates:
             - Path=/payment/lb/***
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka