# 端口号信息
server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystirx-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud2021?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  devtools:
    restart:
      enabled: true #是否支持热部署

#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1 # 采样率在0~1之间，1表示全部采样
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 300000 #发送心跳时间
#    lease-expiration-duration-in-seconds: 900000 #最后异常发送心跳的时间

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.example.entities    # 所有Entity别名类所在包
